AliceO2Group/analysis-framework

framework.md

Hi, I refreshed the doc a little:
- updated some code samples to current syntax
- added event mixing description
- moved to the end features that are not implemented yet (as of my knowledge)
I think some description of new expression columns and configurables could be added here as well. I am not sure if anything more is missing?

Updated framework.md

---

index.md
pid.md

@jgrosseo I added few description lines and how-to's

Add PID documentation

---

docs/framework/framework.md
docs/tutorials/histogramRegistry.md

. update of Configurable
. update of HistogramRegistry

update of Configurable and HistogramRegistry

---

docs/framework/pwghf.md

PWGHF: Update links and add new workflows

---

docs/framework/pwgdq.md

Indico links to the hands-on session

Adding a link to the hands-on session

---

docs/framework/framework.md

add note warning readers that filtering cannot be used on dynamic columns

Data Processing - no filtering on dynamic columns

---

docs/framework/framework.md

Added information about the use of json files for configuration
I am not sure if I put it in the right place though

config json files

---

docs/framework/workingWithCCDB.md

Adding basic commands to download-upload CCDB

Adding basic commands to download-upload CCDB

---

docs/basics-usage/HelperTasks.md

@ddobrigk @jgrosseo here the updated documentation after the structure changes.

Update trackselection doc. with Run 3 ITS requirements.

---

docs/basics-usage/DownloadingFiles.md

Add some brief description for file copy capabilities of alien.py and add link to alien.py manual. FYI @jgrosseo

DownloadingFiles.md:: add alien.py information

---

docs/advanced-specifics/pwghf.md
docs/datamodel/pwgTables.md

Related PR: https://github.com/AliceO2Group/O2Physics/pull/1469

PWGHF: Introduce the naming scheme

---

docs/hyperloop/operatordocumentation.md

Update derived data type information

---

docs/basics-tasks/IntroductionTables.md

This fixes _some_ broken links introduced in 52bd38beb3.
Not all links could be fixed for this site due the deletion in 17d13bc82e. It is unclear if these should then simply be removed.
Note: I am not even sure if PRs are welcome here :)
Signed-off-by: Felix Schlepper <f3sch.git@outlook.com>

IntroductionTables: Fix links to datamodel

---

docs/hyperloop/userdocumentation.md

Add sections and fix links

---

.github/workflows/mega-linter.yml

Syncing with the fixed version in O2Physics.
Propagating the following fixes:
* https://github.com/AliceO2Group/O2Physics/pull/1545
* https://github.com/AliceO2Group/O2Physics/pull/1617

Fix MegaLinter workflow

---

docs/advanced-specifics/pwgdq.md
docs/advanced-specifics/pwgem.md
docs/basics-tasks/BasicAnalysisTask.md
docs/basics-usage/ReadingTablesFromFile.md
docs/basics-usage/SavingTablesToFile.md
docs/gettingstarted/contributingtodocs.md
docs/gettingstarted/gitbasics.md

- Updated documentation of PWG DQ
- Start documentation of PWG EM
- Added Git-Basics
- Some formatting

Update PWG DQ & EM doc, add Git-Basics, some formatting

---

docs/basics-usage/HelperTasks.md

Linked to O2Physics PR [#1839](https://github.com/AliceO2Group/O2Physics/pull/1839)

Fix track-sel doc. for Run 3 analyses.

---

docs/basics-usage/HelperTasks.md

Improvement in the documentation done after a discussion with Fabio Colamaria.

Clarify track selection doc. for Run 3 analyses.

---

docs/hyperloop/userdocumentation.md

Fix bug in display

---

docs/gettingstarted/gitbasics.md

Add links to tutorials, selected sections and cheat sheets

Improve the Git basics section

---

docs/gettingstarted/installing.md

Update installation commands

---

docs/hyperloop/userdocumentation.md

Section for local O2 execution

---

docs/advanced-specifics/pwghf.md
docs/gettingstarted/contributingtocode.md

Getting started:
- extend contribution instructions
PWGHF:
- extend contribution instructions,
- update links,
- simplify lists of workflows

PWGHF, Getting started: Update links, simplify lists of workflows, extend contribution instructions

---

CPPLINT.cfg

Sync with https://github.com/AliceO2Group/O2Physics/pull/3421

Update cpplint configuration

---

docs/advanced-specifics/eventMixing.md
docs/advanced-specifics/machineLearning.md
docs/advanced-specifics/pwgcf.md
docs/advanced-specifics/pwgdq.md
docs/advanced-specifics/pwgem.md
docs/advanced-specifics/pwghf.md
docs/advanced-specifics/pwgje.md
docs/advanced-specifics/pwglf.md
docs/advanced-specifics/pwgmm.md
docs/advanced-specifics/pwgud.md
docs/advanced-specifics/trackToCollAssoc.md

Added $ symbols for MathJax formatting + Renumbering the different sections

Fix in mathjax + renumbering in the section

---

docs/basics-usage/HelperTasks.md

Update Track tuner documentation

---

docs/basics-usage/HelperTasks.md

Add reference to track tuner vs. phi.
